package com.walit.streamline.Communicate;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ChannelResult extends SearchResult {
    public String author;
    public String authorId;
    public String authorUrl;
    public List<AuthorThumbnail> authorThumbnails;
    public boolean autoGenerated;
    public int subCount;
    public int videoCount;
    public String description;
    public String descriptionHtml;

    public static class AuthorThumbnail {
        public String url;
        public int width;
        public int height;
    }
}
