name: Change "bug" Label for Non-Owner Issues

on:
  issues:
    types:
      - opened

jobs:
  update-bug-label:
    runs-on: ubuntu-latest
    steps:
      - name: Change "bug" label to "bug-unconfirmed" for non-owner issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.STREAMLINE_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const issueCreator = context.payload.issue.user.login;
            const repoOwner = context.repo.owner;

            // Labels to check and replace
            const targetLabel = "bug";
            const replacementLabel = "bug-unconfirmed";

            // Check if the issue creator is the repository owner
            if (issueCreator !== repoOwner) {
              const existingLabels = context.payload.issue.labels.map(label => label.name);
              
              if (existingLabels.includes(targetLabel)) {
                // Remove "bug" and add "bug-unconfirmed"
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  name: targetLabel
                });

                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  labels: [replacementLabel]
                });

                console.log(`Replaced "${targetLabel}" with "${replacementLabel}" for issue #${issueNumber}`);
              } else {
                console.log(`Issue #${issueNumber} does not have the "${targetLabel}" label, no changes made.`);
              }
            } else {
              console.log(`Issue #${issueNumber} was created by the repo owner, no label changes.`);
            }
