name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITLAB_ACCESS_TOKEN }}" -H "Content-Type: application/json" -F "ref=main" "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/pipeline"
