name: Remove Labels on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "currently-being-worked-on" and "finished-waiting-on-merge" labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const labelsToRemove = ["currently-being-worked-on", "finished-waiting-on-merge"];

            const existingLabels = context.payload.issue.labels.map(label => label.name);
            const labelsToActuallyRemove = existingLabels.filter(label => labelsToRemove.includes(label));

            if (labelsToActuallyRemove.length > 0) {
              await github.rest.issues.removeLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: labelsToActuallyRemove
              });
              console.log(`Removed labels ${labelsToActuallyRemove.join(", ")} from issue #${issueNumber}`);
            } else {
              console.log(`No matching labels found to remove on issue #${issueNumber}`);
            }
